# # -*- coding: utf-8 -*-
# # SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
# #
# # SPDX-License-Identifier: MIT

# # This file is used to define the scenarios that are run by snakemake. 
# #Each entry on the first level is a scenario. 
# #Each scenario can contain configuration overrides with 
# #respect to the config/config.yaml settings.
# #
# # Example
# #
# # custom-scenario: # name of the scenario
# #   electricity:
# #       renewable_carriers: [wind, solar] # override the list of renewable carriers


# multi-output scenarios
MB_pyro:
  sector:
    pyrolysis_multi-output:
      enable: true
  biomass:
    scenario: ENS_Med
MB_NOpyro:
  sector:
    pyrolysis_multi-output:
      enable: false
  biomass:
    scenario: ENS_Med

HB_pyro:
  sector:
    pyrolysis_multi-output:
      enable: true
  biomass:
    scenario: ENS_High
HB_NOpyro:
  sector:
    pyrolysis_multi-output:
      enable: false
  biomass:
    scenario: ENS_High

100_pyro:
  sector:
    pyrolysis_multi-output:
      enable: true
    co2_sequestration_potential:
      2050: 100
100_NOpyro:
  sector:
    pyrolysis_multi-output:
      enable: false
    co2_sequestration_potential:
      2050: 100

50_pyro:
  sector:
    pyrolysis_multi-output:
      enable: true
    co2_sequestration_potential:
      2050: 50
50_NOpyro:
  sector:
    pyrolysis_multi-output:
      enable: false
    co2_sequestration_potential:
      2050: 50

0_pyro:
  sector:
    pyrolysis_multi-output:
      enable: true
    co2_sequestration_potential:
      2050: 0


# 2_Pyro_MB:
#   biomass:
#     scenario: ENS_Med

# 2_NOPyro_MB:
#   biomass:
#     scenario: ENS_Med
#   sector:
#     flash_pyrolysis: false
#     slow_pyrolysis_CHP: false
#     slow_pyrolysis_H2: false
