# # -*- coding: utf-8 -*-
# # SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
# #
# # SPDX-License-Identifier: MIT

# # This file is used to define the scenarios that are run by snakemake. 
# #Each entry on the first level is a scenario. 
# #Each scenario can contain configuration overrides with 
# #respect to the config/config.yaml settings.
# #
# # Example
# #
# # custom-scenario: # name of the scenario
# #   electricity:
# #       renewable_carriers: [wind, solar] # override the list of renewable carriers


EU_pyro:
  sector:
    pyrolysis_multi-output:
      enable: true
EU_NOpyro:
  sector:
    pyrolysis_multi-output:
      enable: false


EU_pyro_gas:
  sector:
    pyrolysis_multi-output:
      enable: true
    gas_network: true

EU_NOpyro_gas:
  sector:
    pyrolysis_multi-output:
      enable: false
    gas_network: true

EU_pyro_H2:
  sector:
    pyrolysis_multi-output:
      enable: true
    H2_network: true

EU_NOpyro_H2:
  sector:
    pyrolysis_multi-output:
      enable: false
    H2_network: true

EU_pyro_CO2:
  sector:
    pyrolysis_multi-output:
      enable: true
    co2_spatial: true
    co2_network: true

EU_NOpyro_CO2:
  sector:
    pyrolysis_multi-output:
      enable: false
    co2_spatial: true
    co2_network: true

EU_pyro_Bm_spatial:
  sector:
    pyrolysis_multi-output:
      enable: true
    biomass_spatial: true #change to true


EU_pyro_Bm_spatial_transport:
  sector:
    pyrolysis_multi-output:
      enable: true
    biomass_spatial: true #change to true
    biomass_transport: true